### PR TITLE
Fixed the encoding random hang issue with few threads.

### LINKED ISSUE #474: Encoding randomly hangs with fewer working threads
It's "found" by CI testing, and can be reproduced (1 in 15 probability) by:
./SvtHevcEncApp -i akiyo_cif.y4m -b 0.265 -lp 1

### PR DESCRIPTION
**Pull request by Austin-Hu**
This is an old issue since v1.2.0. Overall it's due to the incorrect
life cycle management of the PPCS, PA RefPic, PCS objects in different
kernels (through ResourceCoordination to EncDec, and PictureManger &
RateControl with feedbacks from EncDec and Packetization separately).

When the random hang happens, the former process is:
1. PPCS A which is referenced by other picture(s) B (& C), has been
   encoded and packetized completely. RateControl releases it after
   getting the feedback back from Packetization;
2. The PPCS A object is enqueued into the head of (the empty queue of)
   PPCS FIFO (for higher cache hit);
3. ResourceCoordination receives a new picture D, dequeues the PPCS
   object (aligned with A) from head of PPCS FIFO, and makes picture D
   go through the latter encoding stages;
4. In PictureDecision, the contents (including isUsedAsReferenceFlag)
   of the PPCS object are updated according to parameters of picture D;
5. Meanwhile in EncDec, PPCS A is still on-going with its latter stuff
   (such as SAO, padding, etc.) after encoding and feedbacking to
   EntropyCoding. But as the isUsedAsReferenceFlag of PPCS object
   belonged to A was changed, A couldn't be fed back to PictureManager.
6. In the inputPictureQueue of PictureManger, picture B (& C) are
   permanently waiting for A to be available;
7. Encoding for latter pictures is blocked (objects from FIFO queues
   exhaust) and hangs.

So the solution is:
(Note: we need to manage the life cycle of PPCS, PA RefPic and PCS
RefPic objects separately, because they're operated in
pictureDecisionPaReferenceQueue of PictureDecision and
referencePictureQueue of PictureManager, besides of other kernels.)

1. In ResourceCoordination, make sure the live count of PPCS and its PA
   RefPic objects are 2, because they will be asynchronously released
   in both EncDec and RateControl kernels;
2. In PictureDecision, increase the dependentPicturesCount of the PA
   RefPic object, when a PPCS is indeed referenced by other picture(s).
   And don't release PPCS and its PA RefPic objects at the end when
   trying to clean up the entries of the pictureDecisionPaReferenceQueue;
3. In InitialRateControl, don't release PPCS and its PA RefPic objects,
   as they'd be used in the following kernels;
4. In PictureManager, increase the refCount of the PCS RefPic object,
   when the PCS indeed references other picture(s);
5. In EncDec, release PPCS and its PA RefPic objects which the encoded
   picture is referencing to, and the encoded picture's PCS RefPic
   object. Also release the encoded picture's PPCS and PA RefPic objects;
6. When PictureManager receives the feedback of Packetization, release
   PPCS and PA RefPic objects of the encoded picture as well.

With the changes, the live count for the PPCS and PA Ref objects in each kernel stage are (numbers in brackets means the current picture is referenced by other picture(s)):

 Obj            |  RC          |  PD           |  EncDec         |   RateControl
 PPCS:         |  2            |  (+1)         |  1 (- 1)           |   0
 PA Ref:       |  2            |  (+1)         |  1 (- 1)           |   0

compared with original implementation:

 Obj            |  RC         |  IRC         |  PD                    |   RateControl
 PPCS:         |  3           |  2            |  1 (+ 1 - 1)         |   0
 PA Ref:       |  2           |  1            |  0 (+ 1 - 1)         |

Signed-off-by: Austin Hu <austin.hu@intel.com>

Fixes #474 .

### CODE REVIEW

**Comment by Austin-Hu** [comment]
> Great to see the comment in there..and good job finding this fix.
> 
> This comment pertains to a lot of the codebase, but it would be great to simplify some of the pointer dereferencing.. e.g. pictureControlSetPtr->ParentPcsPtr->refPaPcsArray[REF_LIST_0] is used in numerous places - might be simpler to read if a local variable was set and then used (e.g.)
> refList0 = pictureControlSetPtr->ParentPcsPtr->refPaPcsArray[REF_LIST_0];
> ...

Thanks, @intelmark . I just followed the style in the kernel implementations, otherwise there'd be too many variables for such kind of dereferencing...

**Comment by Austin-Hu** [comment]
Completed several testing with the PR:
- Full CI:
```
---------------------------------------------------------
Test Begin...
Total Number of Tests: 33750
Total Passed: 33689
Percentage Passed: 99.8192592593%
Time Elapsed: 3 day(s), 18 hour(s), 47 minute(s), 23 second(s)
---------------------------------------------------------
```

CI Failed Cases:
1. asm_test: 24 (old R2R issue, not regression)
2. buffered_test: 21
3. defield_test: 10 (old R2R issue, not regression)
4. multi_channel_test: 6

- Issue #474 verification: encoding didn't hang with > 15 hours (> 27,000 times) repeat running.
- Continuous frames input: encoding didn't hang with > 500,000 input frames.
- Performance: no performance regression, tested with small resolution (352x288) and big resolution (8K, P420 8-bit).

**Comment by Austin-Hu** [comment]
Completed several testing with the PR:
### **Full CI** (No regression):
```
---------------------------------------------------------
Test Begin...
Total Number of Tests: 33750
Total Passed: 33689
Percentage Passed: 99.8192592593%
Time Elapsed: 3 day(s), 18 hour(s), 47 minute(s), 23 second(s)
---------------------------------------------------------
```

  Full CI Failed Cases:
1. asm_test: 24 (old R2R issue, not regression)
2. buffered_test: 21
3. defield_test: 10 (old R2R issue, not regression)
4. multi_channel_test: 6
### **Fast CI (with "-lp 1" option)** (No regression):
```
---------------------------------------------------------
Test Begin...
Total Number of Tests: 2433
Total Passed: 2431
Percentage Passed: 99.9177969585%
Time Elapsed: 13 hour(s), 3 minute(s), 33 second(s)
---------------------------------------------------------
```

  Fast CI (with "-lp 1" option) Failed Cases:
1. multi_channel_test: 2


### **Performance**: some performance drop for small resolution (352x288):

| Input | Command Line | Performance   Argument | Without PR #475 | With PR #475 | 
| -- | -- | -- | -- | --
8K P420 8-bit | ./SvtHevcEncApp -i   8k2D_musician_7680x3840_8bit_30Hz_P420.yuv      -w 7680 -h 3840 -b 0.265 -n 10000 | Average Speed (FPS) | 38.96 | 38.91
| | | Total Encoding Time (ms) | 256673 | 256980
| | | Total Execution Time (ms) | 264407 | 264908
352x288 P420 8-bit | ./SvtHevcEncApp -i akiyo_cif.y4m      -b 0.265 -n 100000 | Average Speed (FPS)  | **539.88** | **457.51**
| | | Total Encoding Time (ms) | **185228** | **218576**
| | | Total Execution Time (ms) | **185409** | **218760**


### **Stress Testing**:
1. Issue #474 verification: encoding didn't hang with > 15 hours (> 27,000 times) repeat running.
2. Continuous frames input: encoding didn't hang with > 500,000 input frames.

**Comment by Austin-Hu** [comment]
As for some performance drop "side effect" with small resolution (such as 352x288), it's because only the PPCS and PA Ref objects which are not referenced by other picture(s) any more can be dequeued from their corresponding FIFOs, rather than that the ones which are still referenced by other picture(s) could be dequeued without this PR applied. So by enlarging the length of those FIFOs, the encoding performance can be increased to ~600 FPS:
```
diff --git a/Source/Lib/Codec/EbEncHandle.c b/Source/Lib/Codec/EbEncHandle.c
index 3ca232a..853f9d3 100644
--- a/Source/Lib/Codec/EbEncHandle.c
+++ b/Source/Lib/Codec/EbEncHandle.c
@@ -1960,10 +1960,10 @@ void LoadDefaultBufferConfigurationSettings(
     sequenceControlSetPtr->tileGroupRowCountArray[5] = tileGroupRowCount;

     //#====================== Data Structures and Picture Buffers ======================
-    sequenceControlSetPtr->pictureControlSetPoolInitCount       = inputPic;
+    sequenceControlSetPtr->pictureControlSetPoolInitCount       = inputPic * 2;
     sequenceControlSetPtr->pictureControlSetPoolInitCountChild  = MAX(4, coreCount / 6);
     sequenceControlSetPtr->referencePictureBufferInitCount      = inputPic;//MAX((EB_U32)(sequenceControlSetPtr->inputOutputBufferFifoInitCount >> 1), (EB_U32)((1 << sequenceControlSetPtr->staticConfig.hierarchicalLevels) + 2));
-    sequenceControlSetPtr->paReferencePictureBufferInitCount    = inputPic;//MAX((EB_U32)(sequenceControlSetPtr->inputOutputBufferFifoInitCount >> 1), (EB_U32)((1 << sequenceControlSetPtr->staticConfig.hierarchicalLevels) + 2));
+    sequenceControlSetPtr->paReferencePictureBufferInitCount    = inputPic * 2;//MAX((EB_U32)(sequenceControlSetPtr->inputOutputBufferFifoInitCount >> 1), (EB_U32)((1 << sequenceControlSetPtr->staticConfig.hierarchicalLevels) + 2));
     sequenceControlSetPtr->reconBufferFifoInitCount             = sequenceControlSetPtr->referencePictureBufferInitCount;

     //#====================== Inter process Fifos ======================
```

**Comment by Austin-Hu** [comment]
> As for some performance drop "side effect" with small resolution (such as 352x288), it's because only the PPCS and PA Ref objects which are not referenced by other picture(s) any more can be dequeued from their corresponding FIFOs, rather than that the ones which are still referenced by other picture(s) could be dequeued without this PR applied. So by enlarging the length of those FIFOs, the encoding performance can be increased to ~600 FPS:
> 
> ```
> diff --git a/Source/Lib/Codec/EbEncHandle.c b/Source/Lib/Codec/EbEncHandle.c
> index 3ca232a..853f9d3 100644
> --- a/Source/Lib/Codec/EbEncHandle.c
> +++ b/Source/Lib/Codec/EbEncHandle.c
> @@ -1960,10 +1960,10 @@ void LoadDefaultBufferConfigurationSettings(
>      sequenceControlSetPtr->tileGroupRowCountArray[5] = tileGroupRowCount;
> 
>      //#====================== Data Structures and Picture Buffers ======================
> -    sequenceControlSetPtr->pictureControlSetPoolInitCount       = inputPic;
> +    sequenceControlSetPtr->pictureControlSetPoolInitCount       = inputPic * 2;
>      sequenceControlSetPtr->pictureControlSetPoolInitCountChild  = MAX(4, coreCount / 6);
>      sequenceControlSetPtr->referencePictureBufferInitCount      = inputPic;//MAX((EB_U32)(sequenceControlSetPtr->inputOutputBufferFifoInitCount >> 1), (EB_U32)((1 << sequenceControlSetPtr->staticConfig.hierarchicalLevels) + 2));
> -    sequenceControlSetPtr->paReferencePictureBufferInitCount    = inputPic;//MAX((EB_U32)(sequenceControlSetPtr->inputOutputBufferFifoInitCount >> 1), (EB_U32)((1 << sequenceControlSetPtr->staticConfig.hierarchicalLevels) + 2));
> +    sequenceControlSetPtr->paReferencePictureBufferInitCount    = inputPic * 2;//MAX((EB_U32)(sequenceControlSetPtr->inputOutputBufferFifoInitCount >> 1), (EB_U32)((1 << sequenceControlSetPtr->staticConfig.hierarchicalLevels) + 2));
>      sequenceControlSetPtr->reconBufferFifoInitCount             = sequenceControlSetPtr->referencePictureBufferInitCount;
> 
>      //#====================== Inter process Fifos ======================
> ```

Addressed the "side effect" by [commit](https://github.com/OpenVisualCloud/SVT-HEVC/pull/475/commits/8c029e680955a1f6109d5c13e9d6b16bd2290452).

File: Source/Lib/Codec/EbEncHandle.c [hunk 1]
```diff
@@ -1960,10 +1967,19 @@ void LoadDefaultBufferConfigurationSettings(
     sequenceControlSetPtr->tileGroupRowCountArray[5] = tileGroupRowCount;
 
     //#====================== Data Structures and Picture Buffers ======================
-    sequenceControlSetPtr->pictureControlSetPoolInitCount       = inputPic;
+    if (inputResolution <= INPUT_SIZE_1080p_RANGE)
+        sequenceControlSetPtr->pictureControlSetPoolInitCount       = inputPic * 2;
```
Comment (intelmark) [inline Source/Lib/Codec/EbEncHandle.c]: Maybe use a constant with a meaningful name instead of just a hardcoded "2"

File: Source/Lib/Codec/EbEncHandle.c [hunk 2]
```diff
@@ -1960,10 +1967,19 @@ void LoadDefaultBufferConfigurationSettings(
...
+    else
+        sequenceControlSetPtr->pictureControlSetPoolInitCount       = inputPic;
+
     sequenceControlSetPtr->pictureControlSetPoolInitCountChild  = MAX(4, coreCount / 6);
     sequenceControlSetPtr->referencePictureBufferInitCount      = inputPic;//MAX((EB_U32)(sequenceControlSetPtr->inputOutputBufferFifoInitCount >> 1), (EB_U32)((1 << sequenceControlSetPtr->staticConfig.hierarchicalLevels) + 2));
-    sequenceControlSetPtr->paReferencePictureBufferInitCount    = inputPic;//MAX((EB_U32)(sequenceControlSetPtr->inputOutputBufferFifoInitCount >> 1), (EB_U32)((1 << sequenceControlSetPtr->staticConfig.hierarchicalLevels) + 2));
+
+    if (inputResolution <= INPUT_SIZE_1080p_RANGE)
+        sequenceControlSetPtr->paReferencePictureBufferInitCount    = inputPic * 2;//MAX((EB_U32)(sequenceControlSetPtr->inputOutputBufferFifoInitCount >> 1), (EB_U32)((1 << sequenceControlSetPtr->staticConfig.hierarchicalLevels) + 2));
```
Comment (intelmark) [inline Source/Lib/Codec/EbEncHandle.c]: Why are we leaving in commented code?

File: Source/Lib/Codec/EbEncHandle.c (hunk 1 above)
Comment (Austin-Hu) [reply Source/Lib/Codec/EbEncHandle.c]: Resolved.

File: Source/Lib/Codec/EbEncHandle.c (hunk 2 above)
Comment (Austin-Hu) [reply Source/Lib/Codec/EbEncHandle.c]: Resolved.

**Comment by Austin-Hu** [comment]
> Would it make more sense to add a null pointer check to EbReleaseObject?

It's supposed that those PPCS and PA Ref object's corresponding wrappers exist in the EncDec and RateControl processes. Thanks!

File: Source/Lib/Codec/EbInitialRateControlProcess.c [hunk 3]
```diff
@@ -370,42 +370,6 @@ EB_ERRORTYPE InitialRateControlContextCtor(
...
-		for (listIndex = REF_LIST_0; listIndex <= numOfListToSearch; ++listIndex) {
-
-				// Release PA Reference Pictures
-				if (pictureControlSetPtr->refPaPicPtrArray[listIndex] != EB_NULL) {
-
-                    EbReleaseObject(((EbPaReferenceObject_t*)pictureControlSetPtr->refPaPicPtrArray[listIndex]->objectPtr)->pPcsPtr->pPcsWrapperPtr);
-					EbReleaseObject(pictureControlSetPtr->refPaPicPtrArray[listIndex]);
-				}
-		}
-	}
```
Comment (Austin-Hu) [inline Source/Lib/Codec/EbInitialRateControlProcess.c]: Moved this to EncDec kernel (Line 3211 ~ 3223), where the picture(s) referencing to the current PPCS have completed encoding (not used in latter EntropyCoding and Packetization any more).

File: Source/Lib/Codec/EbInitialRateControlProcess.c [hunk 4]
```diff
@@ -370,42 +370,6 @@ EB_ERRORTYPE InitialRateControlContextCtor(
...
-
-	if (pictureControlSetPtr->paReferencePictureWrapperPtr != EB_NULL) {
-
-        EbReleaseObject(pictureControlSetPtr->pPcsWrapperPtr);
-		EbReleaseObject(pictureControlSetPtr->paReferencePictureWrapperPtr);
-	}
```
Comment (Austin-Hu) [inline Source/Lib/Codec/EbInitialRateControlProcess.c]: Moved this to EncDec kernel (Line 3225 ~ 3236), where the current picture has completed encoding (not used in latter EntropyCoding and Packetization any more).

File: Source/Lib/Codec/EbPictureDecisionProcess.c [hunk 5]
```diff
@@ -1359,10 +1362,9 @@ void* PictureDecisionKernel(void *inputPtr)
                 // Remove the entry
                 if((inputEntryPtr->dependentCount == 0) &&
                    (inputEntryPtr->inputObjectPtr)) {
-                    EbReleaseObject(inputEntryPtr->pPcsPtr->pPcsWrapperPtr);
-                       // Release the nominal liveCount value
-                       EbReleaseObject(inputEntryPtr->inputObjectPtr);
```
Comment (Austin-Hu) [inline Source/Lib/Codec/EbPictureDecisionProcess.c]: Shouldn't release the PPCS and its corresponding PA Ref objects here, because it may be still referenced by other pictures.

File: Source/Lib/Codec/EbRateControlProcess.c [hunk 6]
```diff
@@ -2855,14 +2855,16 @@ void* RateControlKernel(void *inputPtr)
...
             totalNumberOfFbFrames++;
 
-			// Release the SequenceControlSet
-			EbReleaseObject(parentPictureControlSetPtr->sequenceControlSetWrapperPtr);
+            // Release the SequenceControlSet
+            EbReleaseObject(parentPictureControlSetPtr->sequenceControlSetWrapperPtr);
             // Release the input buffer
             EbReleaseObject(parentPictureControlSetPtr->ebInputWrapperPtr);
+            // Release the PA Reference Picture
+            EbReleaseObject(parentPictureControlSetPtr->paReferencePictureWrapperPtr);
```
Comment (Austin-Hu) [inline Source/Lib/Codec/EbRateControlProcess.c]: Also released the PA Ref object corresponding to the current PPCS object here.

File: Source/Lib/Codec/EbResourceCoordinationProcess.c [hunk 7]
```diff
@@ -627,14 +627,16 @@ void* ResourceCoordinationKernel(void *inputPtr)
...
-        	pictureControlSetPtr->paReferencePictureWrapperPtr,
-            2);
+                pictureControlSetPtr->paReferencePictureWrapperPtr,
+                2);
 
         EbObjectIncLiveCount(
-            pictureControlSetWrapperPtr,
-            2);
+                pictureControlSetWrapperPtr,
+                1);
```
Comment (Austin-Hu) [inline Source/Lib/Codec/EbResourceCoordinationProcess.c]: So with the PR applied, the live count for the PPCS and PA Ref objects in each kernel stage are (numbers in brackets means the current picture is referenced by other picture(s)):

     Obj           |  RC          |  PD           |  EncDec         |   RateControl
     PPCS:         |  2           |  (+1)         |  1 (- 1)        |   0
     PA Ref:       |  2           |  (+1)         |  1 (- 1)        |   0


Without the PR:

     Obj           |  RC          |  IRC         |  PD                  |   RateControl
     PPCS:         |  3           |  2           |  1 (+ 1 - 1)         |   0
     PA Ref:       |  2           |  1           |  0 (+ 1 - 1)         |

**Comment by tianjunwork** [comment]
`./SvtHevcEncApp -i ../../../../yuv/bbb_1920x1080_420p.yuv -w 1920 -h 1080  -encMode 0 -intra-period 100 -scd 0 -rc 0 -q 22 -n 1000 -b 0.265` random hang.
I wonder if it can be fixed by this PR too.

**Comment by Austin-Hu** [comment]
> `./SvtHevcEncApp -i ../../../../yuv/bbb_1920x1080_420p.yuv -w 1920 -h 1080 -encMode 0 -intra-period 100 -scd 0 -rc 0 -q 22 -n 1000 -b 0.265` random hang.
> I wonder if it can be fixed by this PR too.

Thanks for capturing this!

At first, this is another (fixed, not random) hang issue which hasn't been addressed by this PR, or isn't regression caused by this PR.

And here is the hang pattern due to encMode 0 and intra period:
- ./SvtHevcEncApp -i bbb_1920x1080_420p.yuv -w 1920 -h 1080 **-encMode 0 -intra-period 100** -scd 0 -rc 0 -q 22 -n 1000 -b 0.265
  - hangs after fixed encoded frames 253
- ./SvtHevcEncApp -i /home/austin/VCD/bbb_1920x1080_420p.yuv -w 1920 -h 1080 -intra-period 100 -scd 0 -rc 0 -q 22 -n 1000 -b 0.265
  - hangs after fixed encoded frames 286
- ./SvtHevcEncApp -i /home/austin/VCD/bbb_1920x1080_420p.yuv -w 1920 -h 1080 -intra-period 55 -scd 0 -rc 0 -q 22 -n 1000 -b 0.265
  - Works fine (-intra-period is [recommended](https://github.com/OpenVisualCloud/SVT-HEVC/blob/master/Docs/svt-hevc_encoder_user_guide.md) to set as 55 with 60 FPS encoded)
- ./SvtHevcEncApp -i /home/austin/VCD/bbb_1920x1080_420p.yuv -w 1920 -h 1080 -encMode 0 -scd 0 -rc 0 -q 22 -n 1000 -b 0.265
  - hangs (only for encMode 0) after fixed encoded frames 283

Anyway, it's another hang issue we need to look at.

**Comment by tianjunwork** [comment]
Hi @Austin-Hu , the performance data in above table is without the fixes of fifo size, right? With the fix of PPCS and PA fifo size, cif fps goes up to 600?

**Comment by Austin-Hu** [comment]
> Hi @Austin-Hu , the performance data in above table is without the fixes of fifo size, right? With the fix of PPCS and PA fifo size, cif fps goes up to 600?

Yes, I got the dropped performance data before figuring out this [commit](https://github.com/OpenVisualCloud/SVT-HEVC/pull/475/commits/8c029e680955a1f6109d5c13e9d6b16bd2290452). And with that commit applied as well, there isn't performance gap with the whole PR applied or not.

**Comment by tianjunwork** [comment]
Memory:
|   | 1080p  | cif | 
|---|---|---|
| master allocated memory  | 2.29G  | 899.14 MB  | 
| This PR allocated memory |  2.83G |  940MB | 

Speed:
image

image
