### PR TITLE
Fixed output buffer too small issue

### LINKED ISSUE #64: An error(Error encoding at channel 1! Check error log file for more details ...Segmentation fault) occurred in running the following command line.
Hi,
An error (Error encoding at channel 1! Check error log file for more details ...Segmentation fault) occurred in running the following command line.

SvtHevcEncApp -i Netflix_FoodMarket2_4096x2160_10bit_60Hz_P420.yuv  -b width_height_test_M9_Netflix_FoodMarket2_4096x2160_10bit_60Hz_P420_Q16_TUNE1_4060_1984.265  -errlog width_height_test_M9_Netflix_FoodMarket2_4096x2160_10bit_60Hz_P420_Q16_TUNE1_4060_1984.errlog  -w 4060  -h 1984  -bit-depth 10  -fps 60  -intra-period 55  -n 100  -compressed-ten-bit-format 0  -q 16  -encMode 9  -rc 0  -tune 1

The SVT version we used is v1.3.0 from master.

Thanks!

### PR DESCRIPTION
**Pull request by Austin-Hu**
Signed-off-by: Austin Hu austin.hu@intel.com

Fixes #64 , #458

### CODE REVIEW

File: Source/Lib/Codec/EbEntropyCoding.c [hunk 1]
```diff
@@ -9249,26 +9249,25 @@ EB_ERRORTYPE CodeDolbyVisionRpuMetadata(
...
-	CHECK_REPORT_ERROR(
-		((outputBitstreamPtr->writtenBitsCount >> 3) + (*outputBufferIndex) < (*outputBufferSize)),
-		encodeContextPtr->appCallbackPtr,
-		EB_ENC_EC_ERROR2);
-
-
+    // To guarantee the output stream buffer is big enough.
+    if (((outputBitstreamPtr->writtenBitsCount >> 3) + (*outputBufferIndex) > (*outputBufferSize)) && *outputBuffer) {
+        free(*outputBuffer);
+        *outputBuffer = (EB_BYTE)malloc((outputBitstreamPtr->writtenBitsCount >> 3) + (*outputBufferIndex));
```
Comment (hassount) [inline Source/Lib/Codec/EbEntropyCoding.c]: need to add a null pointer check here

Comment (Austin-Hu) [reply Source/Lib/Codec/EbEntropyCoding.c]: Resolved in the latter commit.
