### PR TITLE
Fix hang caused by OUT_ALLOC and remove macro

### LINKED ISSUE #514: Encoding hangs with OUT_ALLOC enabled
It's suggested to renable OUT_ALLOC by reverting PR #494 , some encoding would hang such as:
```
./SvtHevcEncApp -i bbb_1920x1080_420p.yuv -w 1920 -h 1080 -n 5000 -hierarchical-levels 0
```

Because randomly POC 278 (279 or 280) could be posted from EntropyCoding kernel, but they couldn't go through (single thread) Packetization which already hangs to dequeue the object from Output FIFO when handling latter pictures (such as POC 405) which may enter Packetization ahead of POC 278.

### PR DESCRIPTION
**Pull request by tianjunwork**
1. The reason of hang caused by OUT_ALLOC is lack of available output stream buffer.
   The fix is to seperate the outputBufferFifoInitCount from inputOutputBufferFifoInitCount.
   And increase its size.
2. Remove the OUT_ALLOC macro.

Signed-off-by: Jun Tian <jun.tian@intel.com>

closes #514, #497

### CODE REVIEW

**Comment by tianjunwork** [comment]
Memory allocated at init.
|   |  1080p |  4k | 8k  |
|---|---|---|---|
| with this PR  | 3.91GB  | 13.45GB  | 47.21GB  | 
| master  | 4.24GB  |  13.9GB |  48.11GB |

File: Source/Lib/Codec/EbEncHandle.c [hunk 1]
```diff
@@ -3958,10 +3953,8 @@ EB_ERRORTYPE EbOutputBufferHeaderCreator(
     }
 
 	// Initialize Header
+    // pBuffer is allocated in PK
```
Comment (intelmark) [inline Source/Lib/Codec/EbEncHandle.c:3956]: is spacing correct?

File: Source/Lib/Codec/EbDefinitions.h [hunk 2]
```diff
@@ -12,7 +12,6 @@ extern "C" {
 #endif
 
 #define PAREF_OUT 1 // Disconnect pa ref  from input for both single/multi core
-#define OUT_ALLOC 0 // Output bitsream allocation at run time for both single/multi core
```
Comment (Austin-Hu) [inline Source/Lib/Codec/EbDefinitions.h:15]: It's better to temporarily keep the macro here, for some issue's regression checking more easily, just in case.

File: Source/Lib/Codec/EbPacketizationProcess.c [hunk 3]
```diff
@@ -612,20 +606,21 @@ void* PacketizationKernel(void *inputPtr)
...
+                pictureControlSetPtr->bitstreamPtr->outputBitstreamPtr);
+
+            // Copy Buffering Period SEI to the Output Bitstream
+            CopyRbspBitstreamToPayload(
+                pictureControlSetPtr->bitstreamPtr,
+                &outputStreamPtr->pBuffer,
+                (EB_U32*) &(outputStreamPtr->nFilledLen),
+                (EB_U32*) &(outputStreamPtr->nAllocLen),
+                encodeContextPtr,
+                NAL_UNIT_INVALID);
```
Comment (Austin-Hu) [inline Source/Lib/Codec/EbPacketizationProcess.c:621]: How about separating the PK logic correction into another PR or commit? Because it's different with the OUT_ALLOC related codes.

File: Source/Lib/Codec/EbEncHandle.c (hunk 1 above)
Comment (tianjunwork) [reply Source/Lib/Codec/EbEncHandle.c:3956]: Mine is correct. The lines around is tab. Tab will be replaced by space in #302.

File: Source/Lib/Codec/EbPacketizationProcess.c (hunk 3 above)
Comment (tianjunwork) [reply Source/Lib/Codec/EbPacketizationProcess.c:621]: will do

File: Source/Lib/Codec/EbDefinitions.h (hunk 2 above)
Comment (tianjunwork) [reply Source/Lib/Codec/EbDefinitions.h:15]: with output buffer size increased to 5000, we can use the old logic anymore. AV1 also removed out_alloc macro.

**Comment by tianjunwork** [comment]
Finished test with -n 1000. No new failed cases other than the existing issues. 
---------------------------------------------------------
Test Begin... 
Total Number of Tests: 2685
Total Passed: 2671
Percentage Passed: 99.47858473%
Time Elapsed: 1 day(s), 23 hour(s), 56 minute(s), 39 second(s)
---------------------------------------------------------
asm_test.txt:------------Failed-------------
asm_test.txt:------------Failed-------------
asm_test.txt:------------Failed-------------
asm_test.txt:------------Failed-------------
buffered_test.txt:------------Failed-------------
buffered_test.txt:------------Failed-------------
buffered_test.txt:------------Failed-------------
buffered_test.txt:------------Failed-------------
defield_test.txt:------------Failed-------------
defield_test.txt:------------Failed-------------
defield_test.txt:------------Failed-------------
defield_test.txt:------------Failed-------------
multi_channel_test.txt:------------Failed-------------
multi_channel_test.txt:------------Failed-------------

**Comment by tianjunwork** [comment]
Hi @intelmark @Austin-Hu , good to go?

**Comment by intelmark** [comment]
looks good! (aside from those test failures which we'll tackle separately)
