### PR TITLE
Fixed the core dump issue with only 1 frame input.

### LINKED ISSUE #413: [SVT-HEVC] SvtHevcEncApp v1.4.1 core-dump occurred when encode
<Test environment>
OS: Ubuntu 18.04 LTS (GNU/Linux 4.15.0-20-generic x86_64)

GCC: gcc version 7.3.0 (Ubuntu 7.3.0-27ubuntu1~18.04)
SVT CommitID: 228d8ef

Verify SVT-HEVC sample binary SvtHevcEncApp with Commit ID 228d8ef, with an 1 frame input yuv stream, then segmentation fault (core dumped) occurred.

- Input stream:
Please ref the attachment file 'input_stream.zip' below, target input "car_output.yuv" is generated from the other one 'car-detection_3840_2160_16s_1frame.mp4' by pure decode. 
Tips: only one frame in the video.
[input_stream.zip](https://github.com/OpenVisualCloud/SVT-HEVC/files/3808325/input_stream.zip)

- Command line:
./SvtHevcEncApp -i ./car_output.yuv -w 3840 -h 2160 -fps-num 25 -fps-denom 1 -tbr 5000000 -rc 1 -intra-period 29 -tune 1 -encMode 1 -profile  -hierarchical-levels 0 -irefresh-type 2 -n 1 -b output.bin
Tips: using deprecated param "tune" and with a blank value for param "profile".

- Captures with different version:

Problem occurred (228d8ef):
CoreDump_v1 4 1_228d8ef

Problem occurred (tag v1.4.1 02fd126):
CoreDump_v1 4 1_release

No problem (tag v1.4.0 ca499c9):
Safe_v1 4 0_release

No problem (tag v1.3.0 60076f7):
Safe_v1 3 0_release

- Bug basic analysis:

GDB information as below:

> [Thread debugging using libthread_db enabled]
>Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
>Core was generated by `./SvtHevcEncApp -i ./car_output.yuv -w 3840 -h 2160 -fps-num 25 -fps-denom 1 -t'.
>Program terminated with signal SIGSEGV, Segmentation fault.
>#0  0x00007f2fef58ab24 in ApplySaoOffsetsPicture (contextPtr=contextPtr@entry=0x5621fd1ddd20, sequenceControlSetPtr=sequenceControlSetPtr@entry=0x5621404cf7b0,
    pictureControlSetPtr=pictureControlSetPtr@entry=0x5621b1400bd0) at /home/berta/sgc/SVT-HEVC/Source/Lib/Codec/EbEncDecProcess.c:569
569                     tbOriginX = lcuParams->originX;
>[Current thread is 1 (Thread 0x7f2d94872700 (LWP 74179))]
>(gdb)

L569~L573,  originX / originY / width / height  may use invalid pointer.

### PR DESCRIPTION
**Pull request by Austin-Hu**
(When receiving only 1 frame input, )SvtHevcEncApp or any application
may invokes EbDeinitEncoder() ahead of all the kernel threads complete
processing. And EbDeinitEncoder() would free all the recorded memory
objects which may be still used by some threads, so that race condition
happens.

So fixed (worked around) this issue by terminating the kernel threads
before freeing memories. Ideally, there should be some object reference
and unreference mechanism to make the objects access safe.

Note:
  1. EbObjectIncLiveCount() couldn't be helpful to address such race
     condition, because it just avoids that an EbObjectWrapper_t object
     wouldn't be returned back to an empty queue prematurely;
  2. EB_SEND_END_OBJ() plus EB_CHECK_END_OBJ() (induced in PR #270) could
     not avoid such race condition, either. Because the objects can be
     freed at any moment when a kernel thread is running and needs to
     access to it.

Signed-off-by: Austin Hu <austin.hu@intel.com>

Fixes #413  .

### CODE REVIEW

**Comment by tianjunwork** [comment]
Fixes #413

File: Source/Lib/Codec/EbEncHandle.c [hunk 1]
```diff
@@ -1947,37 +1947,53 @@ EB_API EB_ERRORTYPE EbDeinitEncoder(EB_COMPONENTTYPE *h265EncComponent)
...
+                    break;
+                }
+            }
+
+            for (ptrIndex = (encHandlePtr->memoryMapIndex) - 1; ptrIndex >= 0; --ptrIndex) {
+                memoryEntry = &encHandlePtr->memoryMap[ptrIndex];
+                switch (memoryEntry->ptrType) {
+                case EB_N_PTR:
+                    free(memoryEntry->ptr);
+                    //memoryEntry->ptr = EB_NULL;
```
Comment (intelmark) [inline Source/Lib/Codec/EbEncHandle.c]: Does comment need to stay or can it be deleted?

Comment (Austin-Hu) [reply Source/Lib/Codec/EbEncHandle.c]: I forgot to remove it.

**Comment by Austin-Hu** [comment]
> Hi Austin, it needs to be `Fixes #413` to auto close #413

It's in the last line of the 1st comment.

**Comment by tianjunwork** [comment]
> > Hi Austin, it needs to be `Fixes #413` to auto close #413
> 
> It's in the last line of the 1st comment.

As Chris pointed out before in #408, it has to be certain format so that Github can read.
It has to be `Fixes #413`. Your last line doesn't work.

**Comment by Austin-Hu** [comment]
> > > Hi Austin, it needs to be `Fixes #413` to auto close #413
> > 
> > 
> > It's in the last line of the 1st comment.
> 
> As Chris pointed out before in #408, it has to be certain format so that Github can read.
> It has to be `Fixes #413`. Your last line doesn't work.

Thanks! Edited it.
